### ISSUE TITLE
Help Wanted: Customizing crafting recipes

### ISSUE THREAD

**Issue by wicivo** [tayadev/Invisible-Item-Frames#1]
Hi, I liked your datapack, but I would like to change the kraft to this, can you help me with that? Please
![image](https://user-images.githubusercontent.com/116191734/218686159-85a0ac2e-797b-4cd9-b6b7-3b6f4c0fa795.png)

My discord for convenience:  NerdTo#5162

**Comment by tayacrystals** [comment]
You can replace the recipe file in the datapack with any custom recipe you would like it to be. The recipe file(s) are located at `data/invisibleitemframes/recipes/invisible_item_frame.json` and `.../invisible_glow_item_frame.json`, just make sure the result item is a `knowledge_book`. I assume for your proposed recipe you would want to add a lingering potion of invisibility, which is actually also sth I considered whilst making the pack, sadly you can't specify what kind of potion a crafting recipe requires, so the best one could do is to have it accept *any* kind of lingering potion.

Here is an example how such a recipe would look:
```json
{
  "type": "crafting_shaped",
  "key": {
    "I": {
       "item": "item_frame"
    },
    "P": {
      "item": "lingering_potion"
    }
  },
  "pattern": [
    "III",
    "IPI",
    "III"
  ],
  "result": {
      "item": "minecraft:knowledge_book",
      "count": 8
  }
}
```

If you need further reference on how minecraft recipes work you can take a look at the corresponding wiki page: https://minecraft.fandom.com/wiki/Recipe

And if you prefer using a visual interface to generate the file for you, instead of typing out the JSON file manually, here are some helpful websites: https://misode.github.io/recipe/, https://crafting.thedestruc7i0n.ca/

Hope this helps :)

PS:
I recommend you give issues you create on github projects more descriptive names. like "Help Wanted: Customizing crafting recipes"

**Comment by wicivo** [comment]
>  Thanks
